package com.tomyn.prusatag

/**
 * Correspondances numeriques -> noms lisibles, extraites de la specification officielle
 * OpenPrintTag (github.com/OpenPrintTag/openprinttag-specification, licence MIT).
 * Genere automatiquement a partir des fichiers YAML de la spec (main_fields.yaml,
 * material_class_enum.yaml, material_type_enum.yaml, tags_enum.yaml) - a regenerer si
 * la spec officielle evolue plutot qu'a modifier a la main.
 */
object ChampsOpenPrintTag {

val nomsChamps = mapOf(
    0 to "instance_uuid",
    1 to "package_uuid",
    2 to "material_uuid",
    3 to "brand_uuid",
    4 to "gtin",
    5 to "brand_specific_instance_id",
    6 to "brand_specific_package_id",
    7 to "brand_specific_material_id",
    8 to "material_class",
    9 to "material_type",
    10 to "material_name",
    11 to "brand_name",
    13 to "write_protection",
    14 to "manufactured_date",
    15 to "expiration_date",
    16 to "nominal_netto_full_weight",
    17 to "actual_netto_full_weight",
    18 to "empty_container_weight",
    19 to "primary_color",
    20 to "secondary_color_0",
    21 to "secondary_color_1",
    22 to "secondary_color_2",
    23 to "secondary_color_3",
    24 to "secondary_color_4",
    27 to "transmission_distance",
    28 to "tags",
    29 to "density",
    31 to "hardness_shore_a",
    32 to "hardness_shore_d",
    34 to "min_print_temperature",
    35 to "max_print_temperature",
    36 to "preheat_temperature",
    37 to "min_bed_temperature",
    38 to "max_bed_temperature",
    39 to "min_chamber_temperature",
    40 to "max_chamber_temperature",
    41 to "chamber_temperature",
    42 to "container_width",
    43 to "container_outer_diameter",
    44 to "container_inner_diameter",
    45 to "container_hole_diameter",
    46 to "viscosity_18c",
    47 to "viscosity_25c",
    48 to "viscosity_40c",
    49 to "viscosity_60c",
    50 to "container_volumetric_capacity",
    51 to "cure_wavelength",
    52 to "material_abbreviation",
    53 to "nominal_full_length",
    54 to "actual_full_length",
    55 to "country_of_origin",
    56 to "certifications",
    57 to "drying_temperature",
    58 to "drying_time",
    59 to "primary_color_lab",
    60 to "primary_color_ral",
    61 to "filament_diameter_v2",
    62 to "min_nozzle_diameter_v2",
)

val materialClass = mapOf(
    0 to "FFF",
    1 to "SLA",
)

val materialType = mapOf(
    0 to "PLA",
    1 to "PETG",
    2 to "TPU",
    3 to "ABS",
    4 to "ASA",
    5 to "PC",
    6 to "PCTG",
    7 to "PP",
    8 to "PA6",
    9 to "PA11",
    10 to "PA12",
    11 to "PA66",
    12 to "CPE",
    13 to "TPE",
    14 to "HIPS",
    15 to "PHA",
    16 to "PET",
    17 to "PEI",
    18 to "PBT",
    19 to "PVB",
    20 to "PVA",
    21 to "PEKK",
    22 to "PEEK",
    23 to "BVOH",
    24 to "TPC",
    25 to "PPS",
    26 to "PPSU",
    27 to "PVC",
    28 to "PEBA",
    29 to "PVDF",
    30 to "PPA",
    31 to "PCL",
    32 to "PES",
    33 to "PMMA",
    34 to "POM",
    35 to "PPE",
    36 to "PS",
    37 to "PSU",
    38 to "TPI",
    39 to "SBS",
    40 to "OBC",
    41 to "EVA",
    42 to "PA612",
)

val nomsTags = mapOf(
    0 to "filtration_recommended",
    1 to "biocompatible",
    2 to "antibacterial",
    3 to "air_filtering",
    4 to "abrasive",
    5 to "foaming",
    6 to "self_extinguishing",
    7 to "paramagnetic",
    8 to "radiation_shielding",
    9 to "high_temperature",
    10 to "esd_safe",
    11 to "conductive",
    12 to "blend",
    13 to "water_soluble",
    14 to "ipa_soluble",
    15 to "limonene_soluble",
    16 to "matte",
    17 to "silk",
    19 to "translucent",
    20 to "transparent",
    21 to "iridescent",
    22 to "pearlescent",
    23 to "glitter",
    24 to "glow_in_the_dark",
    25 to "neon",
    26 to "illuminescent_color_change",
    27 to "temperature_color_change",
    28 to "gradual_color_change",
    29 to "coextruded",
    30 to "contains_carbon",
    31 to "contains_carbon_fiber",
    32 to "contains_carbon_nano_tubes",
    33 to "contains_glass",
    34 to "contains_glass_fiber",
    35 to "contains_kevlar",
    36 to "contains_stone",
    37 to "contains_magnetite",
    38 to "contains_organic_material",
    39 to "contains_cork",
    40 to "contains_wax",
    41 to "contains_wood",
    42 to "contains_bamboo",
    43 to "contains_pine",
    44 to "contains_ceramic",
    45 to "contains_boron_carbide",
    46 to "contains_metal",
    47 to "contains_bronze",
    48 to "contains_iron",
    49 to "contains_steel",
    50 to "contains_silver",
    51 to "contains_copper",
    52 to "contains_aluminium",
    53 to "contains_brass",
    54 to "contains_tungsten",
    55 to "imitates_wood",
    56 to "imitates_metal",
    57 to "imitates_marble",
    58 to "imitates_stone",
    59 to "lithophane",
    60 to "recycled",
    61 to "home_compostable",
    62 to "industrially_compostable",
    63 to "bio_based",
    64 to "low_outgassing",
    65 to "without_pigments",
    66 to "contains_algae",
    67 to "castable",
    68 to "contains_ptfe",
    69 to "limited_edition",
    70 to "emi_shielding",
    71 to "high_speed",
    72 to "contains_graphene",
    73 to "uv_resistant",
    74 to "acetone_soluble",
)


    fun nomChamp(cle: Int): String = nomsChamps[cle] ?: "champ_inconnu_$cle"
}
